name: base
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anaconda-anon-usage=0.5.0=py312hfc23b7f_100
  - anaconda_powershell_prompt=1.1.0=haa95532_0
  - anaconda_prompt=1.1.0=haa95532_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - boltons=23.0.0=py312haa95532_0
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.1.31=h56e8100_0
  - certifi=2025.1.31=py312haa95532_0
  - cffi=1.17.1=py312h827c3e9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.2=pyhd8ed1ab_1
  - conda=25.1.1=py312h2e8e312_0
  - conda-anaconda-telemetry=0.1.1=py312haa95532_0
  - conda-content-trust=0.2.0=py312haa95532_1
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312haa95532_0
  - conda-package-streaming=0.11.0=py312haa95532_0
  - cryptography=43.0.3=py312hbd6ee87_1
  - debugpy=1.8.12=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - distro=1.9.0=py312haa95532_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h8ddb27b_0
  - fmt=9.1.0=h6d14046_1
  - frozendict=2.4.2=py312haa95532_0
  - idna=3.7=py312haa95532_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.32.0=pyh9ab4c32_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonpatch=1.33=py312haa95532_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=py312h2e8e312_0
  - krb5=1.21.3=hdf4eb48_0
  - libarchive=3.7.4=h9243413_0
  - libcurl=8.9.1=h0416ee5_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.16=h2bbff1b_3
  - libmamba=1.5.11=h99b1521_0
  - libmambapy=1.5.11=py312hcd6fe79_0
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.24=h23ce68f_1
  - libsqlite=3.48.0=h67fdade_1
  - libssh2=1.11.1=h2addb87_0
  - libxml2=2.13.5=h24da03e_0
  - libzlib=1.2.13=h2466b09_6
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - menuinst=2.2.0=py312h5da7b33_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.2.2=py312hfd52020_0
  - numpy-base=2.2.2=py312h4dde369_0
  - openssl=3.4.0=ha4e3fda_1
  - packaging=24.1=py312haa95532_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - pluggy=1.5.0=py312haa95532_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=6.1.1=py312h4389bb4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h2bbff1b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.12=5_cp312
  - pywin32=307=py312h275cf98_3
  - pyzmq=26.2.1=py312hd7027bb_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.3=py312haa95532_1
  - ruamel.yaml=0.18.6=py312h827c3e9_0
  - ruamel.yaml.clib=0.2.8=py312h827c3e9_0
  - setuptools=72.1.0=py312haa95532_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py312h4389bb4_0
  - tqdm=4.66.5=py312hfc267ef_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.8.0=py312haa95532_0
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - urllib3=2.2.3=py312haa95532_0
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=h6356254_24
  - vs2015_runtime=14.42.34433=hfef2bbc_24
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml-cpp=0.8.0=hd77b12b_1
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h2466b09_6
  - zstandard=0.23.0=py312h4fc1ca9_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - filelock==3.17.0
      - fsspec==2025.2.0
      - graphviz==0.20.3
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - psycopg2-binary==2.9.10
      - sympy==1.13.1
      - torch==2.6.0
      - torchviz==0.0.3
prefix: C:\Users\CJRGr\miniconda3
